sudo: required

services:
  - docker

env:
  global:
    - NAME=ke20/symfony-cli
    - VERSION=${TRAVIS_BRANCH}

script:
  - docker build -t ${NAME}:${VERSION} --rm image

after_success:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
    docker push ${NAME}:${VERSION};
