sudo: required

services:
  - docker

env:
  global:
    - NAME=ke20/symfony-cli
    - VERSION=${TRAVIS_BRANCH}

script:
  - docker build -t ${NAME}:${VERSION} --rm image

after_success:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}";
    docker push ${NAME}:${VERSION};
